version: '3.7'

services:
  teamspeak:
    image: teamspeak
    container_name: teamspeak
    hostname: teamspeak
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: mariadb
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: teamspeak
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    networks:
      - teamspeak
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10
    container_name: teamspeak-mariadb
    hostname: teamspeak-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teamspeak
      MYSQL_DATABASE: teamspeak
    networks:
      - teamspeak

networks:
  teamspeak:
