version: '3.7'

services:
  teamspeak:
    image: teamspeak
    container_name: teamspeak
    hostname: teamspeak
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_LICENSE: accept
    networks:
      - teamspeak

networks:
  teamspeak:
